version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    user: root
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=primaryReplica
    volumes:
      - ./datafiles:/bitnami
      - ./config:/opt/bitnami/mongodb/conf
    ##depends_on:
     ## - db-data
      
  ##db-data:
  ##  image: busybox
  ##  volumes:
  ##      - ./datafiles:/bitnami
  ##      - ./config:/opt/bitnami/mongodb/conf
  ##  command:
  ##      - chown -R -1001:1001 /bitnami


  mongodb-secondary-first:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=primaryReplica
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary-first
      
  mongodb-secondary-second:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=primaryReplica
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary-second
      
  mongodb-secondary-third:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=primaryReplica
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary-third

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=primaryReplica
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      