version: '2'
services:

    # SHARD 1
    
    shard1_replica1:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard1
            SHARD_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/shard1/replica1:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
            
#    shard1_replica2:
#        image: khezen/mongo:slim
#        environment:
#            RS_NAME: shard1
#            SHARD_SVR: 'y'
#            AUTH: 'y'
#        volumes:
#             - ./data/mongo/shard1/replica2:/data/db
#        restart: always
#        networks:
#            - mongo_cluster2
#            
    shard1_arbiter:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard1
            SHARD_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/shard1/arbiter:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
            
    shard1_replica3:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard1
            SHARD_SVR: 'y'
            MASTER: shard1_replica3
#            SLAVES: shard1_replica1 shard1_replica2
            SLAVES: shard1_replica1
            AUTH: 'y'
            ARBITRERS: shard1_arbiter
        volumes:
             - ./data/mongo/shard1/replica3:/data/db
        restart: always
        networks:
            - mongo_cluster2
        
        
      
  # SHARD 2
  
    shard2_replica1:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard2
            SHARD_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/shard2/replica1:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
            
#    shard2_replica2:
#        image: khezen/mongo:slim
#        environment:
#            RS_NAME: shard2
#            SHARD_SVR: 'y'
#            AUTH: 'y'
#        volumes:
#             - ./data/mongo/shard2/replica2:/data/db
#        restart: always
#        networks:
#            - mongo_cluster2
#            
    shard2_arbiter:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard2
            SHARD_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/shard2/arbiter:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
    shard2_replica3:
        image: khezen/mongo:slim
        environment:
            RS_NAME: shard2
            SHARD_SVR: 'y'
            MASTER: shard2_replica3
#            SLAVES: shard2_replica1 shard2_replica2
            SLAVES: shard2_replica1
            AUTH: 'y'
            ARBITRERS: shard2_arbiter
        volumes:
             - ./data/mongo/shard2/replica3:/data/db
        restart: always
        networks:
            - mongo_cluster2


# CONFIG SVRS


    configsvr1:
        image: khezen/mongo:slim
        environment:
            RS_NAME: configsvr
            CONFIG_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/configsvr/replica1:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
    configsvr2:
        image: khezen/mongo:slim
        environment:
            RS_NAME: configsvr
            CONFIG_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/configsvr/replica2:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
    configsvr_arbiter:
        image: khezen/mongo:slim
        environment:
            RS_NAME: configsvr
            SHARD_SVR: 'y'
            AUTH: 'y'
        volumes:
             - ./data/mongo/configsvr/arbiter:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
    configsvr3:
        image: khezen/mongo:slim
        environment:
            RS_NAME: configsvr
            CONFIG_SVR: 'y'
            MASTER: configsvr3
            SLAVES: configsvr1 configsvr2
            AUTH: 'y'
            ARBITRERS: configsvr_arbiter
        volumes:
             - ./data/mongo/configsvr/replica3:/data/db
        restart: always
        networks:
            - mongo_cluster2
            
    
    
    # MONGOS
    
    
    mongos:
        image: khezen/mongo:slim
        environment:
          CONFIG_SERVERS:  configsvr/configsvr3:27017
          SHARDS: shard1/shard1_replica3 shard2/shard2_replica3
          AUTH: 'y'
          SERVICE_PORTS: 27017
          TCP_PORTS: 27017
        restart: always
        networks:
            - mongo_cluster2
        ports:
            - "27017:27017"
        

networks:
  mongo_cluster2:
    driver: bridge


            


  